### ISSUE TITLE
Elf2K crashes after some time on Linux Ubuntu

### ISSUE THREAD

**Issue by etxmato** [etxmato/emma_02#1]
Seen by Mark, I haven't seen it for a while on Fedora, needs to be debugged

**Comment by etxmato** [comment]
Haven't seen this anymore after adding a wxMutexGuiEnter() on a Panel::ledTimeout (in computer.cpp)

**Comment by phiber1** [comment]
I'll test this as soon as I can...

**Comment by etxmato** [comment]
Thanks Mark, I also made a fix for the error on exit. I had the Elf2K
running for about 1 hour last night and didn't see it on exit...

Started on the GUI look but decided to change to gtk3 first as that might
improve somewhat... with that I ran into repo issues on fedora / update
which are caused by my curl installation (I did not include ssl) anyway
that is fixed now so will re-compile wxwidgets tonight with gtk3.

We also still have the strange cursor blink timing; looked at that but have
no clue what the cause is.

Cheers, Marcel
