### ISSUE TITLE
Elf 2000 Switch Panel has 'pink' buttons, Hex panel needs to be a bit larger

### ISSUE THREAD

**Issue by etxmato** [etxmato/emma_02#11]
On linux only

**Comment by etxmato** [comment]
Pink buttons are also on Membership main window and less have a white background

**Comment by etxmato** [comment]
Same on VELF

**Comment by etxmato** [comment]
Fixed!

**Comment by phiber1** [comment]
Verified, I no longer see pink backgrounds to the buttons.
