### ISSUE TITLE
Segmentation fault when using debugger

### ISSUE THREAD

**Issue by etxmato** [etxmato/emma_02#12]
As soon as the 1802 trace is started in the debugger Emma 02 crashes with a segmentation fault

**Comment by phiber1** [comment]
Confirmed.

**Comment by etxmato** [comment]
Fixed by using the same code as on OSX. This is not perfect, to be honest I was never happy with the OSX solution. The trace is updated on a time basis instead of directly (as on windows). Still we have lived with it on OSX for a few years so I intend to leave it for the coming release. I don't have a better solution at the moment either.
