### ISSUE TITLE
RCA VideoSetup crashes program

### ISSUE THREAD

**Issue by tobiasvl** [etxmato/emma_02#25]
When I click the "VideoSetup" button in the "RCA" tab, Emma 02 crashes with the following error:

![image](https://user-images.githubusercontent.com/80824/67765063-8907ed00-fa4b-11e9-9fcf-45cc1d7e6297.png)

This is Emma 02 V1.32 running on Windows 10. All the other VideoSetup dialogs work as expected.

**Comment by etxmato** [comment]
Should be fixed in V1.33.
