### ISSUE TITLE
Fixes to be done after GUI is fixed

### ISSUE THREAD

**Issue by etxmato** [etxmato/emma_02#3]
Just so I don't forget:
- Check why default window size doesn't open large enough, possible workaround to save size of window and re-open same size
- Set size of wxChoiceBooks to size window
- Update help to use new GUI layout description for: COMX Plot / STD button, Elf Disk vs. File button for IDE.

**Comment by phiber1** [comment]
I'd consider this fixed, as far as initial window size goes. Feel free to close.

**Comment by etxmato** [comment]
Help updates done, window size and wxChoiceBooks size fixed
