### ISSUE TITLE
A proposal for better random generator for SuperChip

### ISSUE THREAD

**Issue by Kouzeru** [etxmato/emma_02#37]
I'm experimenting a bit with how the random numbers are generated on the superchip vm, and...

Seem the numbers generated there do following some patterns and it's pretty short and pretty deterministic. Doesn't look good...
![72mBKgSRqF](https://user-images.githubusercontent.com/46141631/141662715-614d3ad7-fe64-4d7a-acf1-fc96e7e95b62.gif)
![RnMO4J9953](https://user-images.githubusercontent.com/46141631/141662722-0cecb665-04d8-4b24-a918-91128e45dab3.gif)

Expected results are where the **Hex mixt** and **Framed MK1** fills the whole screen:
![pHm3vlY4pp](https://user-images.githubusercontent.com/46141631/141662766-fe1c1be5-b9f6-41c7-8957-5f2dd4220ee4.gif)
![aUnA7VFCL6](https://user-images.githubusercontent.com/46141631/141662771-094656b9-2f5f-4d5d-bae2-f501d9d5639f.gif)

I'm proposing to make use of LSFR [linear shift feedback register] which I think it's good for being simplistic and having more randomness to it. I consider 16-bit LSFR is good, and should be shifted 8 times when fetching one byte from it. (still having period of 65535)

pseudocode
```
seed = 12345 # 16-bit initial feedback value, could be any number

def shift(seed):
 return ((((seed>>1)^seed)<<15)|(seed>>1))&0xFFFF

def shiftByte(seed):
 return shift(shift(shift(shift(shift(shift(shift(shift(seed)))))))) # shift 8 times

# print random bytes 10 times
for n in range(10):
 seed = shiftByte(seed)
 print(seed&255)
```
One may shift it to only few to save cycles, or by making it perform shifts for every chip8 instr executed. It depends on implementation.

**Comment by etxmato** [comment]
As far as I remember I’m using the chip8 random generator which is 8 bit and as such indeed not great. I have 1802 code for a 16 bit random generator; something like your pseudo code but I’m not sure if it will fit into the SuperChip interpreter as space is quite limited…. will investigate…

**Comment by etxmato** [comment]
Hi again, I checked the random code for the SuperChip and it turns out that when I moved the routine to a different location I created a bug... nice find, thanks!

So I didn't change the routine as such, just fixed the bug, it is definitely not that sophisticated but it might do as it is now. Could you give it a try and let me know what you think? I just checked in an updated version
