### ISSUE TITLE
Configuration files are moved when changing Data Directory but loading is always done from original location

### ISSUE THREAD

**Issue by etxmato** [etxmato/emma_02#4]

**Comment by etxmato** [comment]
Should they be moved or always stored in ~/emma_02?

**Comment by phiber1** [comment]
I don't think there's any right answer here, but I'm sort of leaning toward "data" only referring to disk images and related hex files, all of which should be movable, and "Configurations" being separate from that and only referring to the .ini files, which should live in ~/.emma_02 and not be moved.
Just my opinion to keep things more organized.

**Comment by etxmato** [comment]
Configuration files moved to dedicated config folder for all platforms, so issue solved
