### ISSUE TITLE
Changing EOP(End Of Program)

### ISSUE THREAD

**Issue by wel97459** [etxmato/emma_02#41]
When using Memory Access in the comx-35, it should change the EOP to point at the end of the loaded space when SpecifyLocation is check.

EOP is commend in basic and returns the end of program.  It's also used by PSAVE to tell it when to end.

The EOP value is located in memory at 0x4283 high byte and 0x4284 low byte.

![image](https://user-images.githubusercontent.com/12990640/189519453-a2a474c9-52a1-4353-9bb6-7e64f6e3502b.png)

**Comment by etxmato** [comment]
Hi Winston,

Thanks for the feedback but  I don't fully agree. Yes EOP and 0x4283/0x4284 contain the end of a basic program. However the 'Specify Location' feature is to save a specific part of memory. For example if you have some machine code (like the F&M Monitor) somewhere in the end of RAM which you want to save and load directly to that location.

If you turn off the 'Specific Location' check it should save up to EOP, didn't check that but I believe it does. Both PSAVE/DSAVE and memory access features also use 0x4281 (DEFUS), 0x4292/93 (string), 0x4294/95 (array) and 0x4299/0x429A (EOD) so just changing EOP might not give the desired result in all cases. 

With 'Specific Location' checked it will save from start to end as specified and uses the exec address for program start. For the F&M Monitor that would be start=9900, end AF7F and exec A000. i.e. to start you would use CALL(@A000) or the RUN button should do that automatically.

**Comment by wel97459** [comment]
Ya I can see that, i was just loading machine code in to the start of basic code area in ram and psave was only saving up to EOP.

**Comment by etxmato** [comment]
Use DEFUS, for example DEFUS @5000 would reserve BASIC RAM 4400 to 4FFF for your machine code. Then when you write some BASIC, for example 10 CALL(@4401), that code will be stored on @5000. PSAVE, PLOAD and memory access will use this info as well.

**Comment by wel97459** [comment]
ok that does make sense, im a little know to the comx-32 platform.

**Comment by etxmato** [comment]
Feel free to contact me anytime if you have any other questions or feedback on Emma 02 or questions about the COMX!
