### ISSUE TITLE
Comx-35 clock setting

### ISSUE THREAD

**Issue by wel97459** [etxmato/emma_02#43]
I found a bit confusing that instead of the clock setting being the clock speed of the processor.  It's the clock speed before it's dived by 2.
Most of the other systems in the emulator are the clock speed of the processor.  Which really makes more sense as no one is thinking about a pixel clock in an emulator.

**Comment by etxmato** [comment]
Sorry Winston I do not agree. The clock specified is the clock going into the 1802 chip, what the 1802 does with that is another thing. What you are describing is some kind of instruction clock, then I should probably divide by 16. Note these systems, like the COMX were advertised with clock speed as I use.

**Comment by etxmato** [comment]
Ok understood Winston. But the 2.835 is not the video clock; it is the CPU input clock. So the fact that the header tone has a wrong frequency must be another issue. Currently don’t know the cause of it and/or if there is indeed a clock problem. Will investigate …

**Comment by etxmato** [comment]
Hi Winston, sorry have been busy with the Cybervision emulator so I kinda forgot about this problem. I have now compared an original COMX wav file that I had with one created on Emma 02. I do agree the wav output could be improved, the Cybervision output is probably more accurate than the COMX at the moment. But the frequency of the header tone is 2KHz in the file I get generated (as far as I can see). Maybe you can send me a file you created?

On what OS are you running Emma 02?

**Comment by wel97459** [comment]
I'm on Ubuntu Linux. 
I can post a wave file later for you to look at.

**Comment by wel97459** [comment]
Here's A psave out of the Comx-35, clock set at 2.835Mhz. Emma v1.47 on Ubuntu Linux.
[blank.wav](https://cdn.discordapp.com/attachments/568217534160175104/1112998960366358629/blank.wav)

**Comment by etxmato** [comment]
Thanks! I’ll have a look and see if I can reproduce the problem on Linux tonight.

**Comment by etxmato** [comment]
This is strange indeed. I can see your blank.wav (as you said) has a 1K frequency leader tone and when I create one on Linux it is the same as yours. Doing the same on macOS results in a 2K frequency. Speed of the CPU looks correct, so not sure what is going on... I also just compiled the latest beta release which does exactly the same. The latest beta has the new Cybervision 2001 emulator with a more accurate save routine. Now the whole CV emulator has some problems on Linux, so maybe I will try to fix those first and when done I can see how that save compares to macOS and expected frequencies.... this might take a few days.

**Comment by etxmato** [comment]
Just to let you know; the new Cybervision emulator works fine on double clock speed (on Linux). So it looks like the same problem as the COMX tape load/save. However for now I have now idea where it goes wrong. Will continue tomorrow...

**Comment by etxmato** [comment]
I think I found it :). For some reason I have a clock factor of 2 implemented for Linux, this is needed for emulator speed otherwise it runs on half the speed. I copied the same factor for cassette handling which is wrong. I don't really understand why it is needed for sound / emulator speed but not for cassette sound. Anyway when I remove that factor for the cassette handling it works fine.

Here is a ubuntu package for arm: https://github.com/etxmato/emma_02_installation/raw/main/v1.47.14/emma_02_arm.deb. Note this is a beta release, mainly introducing XML handling under the XML tab but none of that is properly documented in the help pages.

I'm starting a x86 build now but that is always a bit cumbersome, not sure when it will be done as I need to run it on emulation on my arm macOS. Code is also committed in the dev branch in case you build it yourself.

**Comment by etxmato** [comment]
Not sure if this one works will try to test it tonight: https://github.com/etxmato/emma_02_installation/raw/main/v1.47.14/emma_02_x64.deb

**Comment by etxmato** [comment]
Managed to mess it up just before I committed the code yesterday. New code committed which I think works, I will restart different linux builds now....

**Comment by etxmato** [comment]
Updated linux packages: 
https://github.com/etxmato/emma_02_installation/raw/main/v1.47.14/emma_02_arm.deb
https://github.com/etxmato/emma_02_installation/raw/main/v1.47.14/emma_02_x64.deb
https://github.com/etxmato/emma_02_installation/raw/main/v1.47.14/emma_02_x64_fedora.rpm
https://github.com/etxmato/emma_02_installation/raw/main/v1.47.14/emma_02_x64_suse.rpm

Sorry, didn't get time to test the packages...

**Comment by etxmato** [comment]
I tested the SUSE package which works ok. The x64.deb package installs on my ubuntu but Emma 02 itself doesn't start for some reason. Possibly something to do with my installation or possibly a problem in the build. Not sure...

**Comment by wel97459** [comment]
Well I can't even get V1.47.14 to output a wave file to test with under Ubuntu.

**Comment by etxmato** [comment]
Did you compile it from GitHub or install my package? I'm assuming you tried it on Ubuntu x64/amd64?
I just checked if I used the correct files in the build and it all looks correct... 

I also ran it on my arm64 Ubuntu which works fine; just tested again and I get wav files.

Not sure where it went wrong... what is it doing if anything? is it starting up and 'just' not creating the wav file? If so it sounds  a bit like the problem I discovered after I committed the first package on Saturday morning....the later packages should have fixed that but maybe not...

**Comment by wel97459** [comment]
I had to default all the configurations, and that got it working.
Thanks for working on this issue.

Also tested it on my FPGA comx-35 core I made and it loaded fine:
![FPGA comx-35 running a game loaded off of tape interface.](https://cdn.discordapp.com/attachments/568217534160175104/1116580998067519508/e67a6377-9b4f-497d-8e41-d5d3f40920e4__01.jpg)

**Comment by etxmato** [comment]
Great and that is looking very cool :)
