### ISSUE TITLE
Bxyn in CHIP-8X not working correctly due to error in interpreter file

### ISSUE THREAD

**Issue by gulrak** [etxmato/emma_02#44]
First thanks for the emulator! It is nice that there is one that takes care of so many exotic systems whit this nice CPU. :-)

While testing VP590 support in my own emulator and comparing behavior of CHIP-8X I found that the `Bxyn` opcode is not working correctly. Debugging the issue showed that the interpreter file in `data/VIP/chip8x.ram` has a bug, I guess it is based on OCR of a hex-dump and somehow the byte at offset `0x228` in the file is `0x9c` but should be `0x8c`, as clearly readable in the [VP580, VP585, VP590, VP595 Instruction Manual](https://github.com/trapexit/chipce8/blob/master/docs/CHIP-8/Misc/VP580%2C%20VP585%2C%20VP590%2C%20VP595%20Instruction%20Manual%20Including%20CHIP-8X.pdf) page II-3.
With that byte changed `Bxyn` works as described.

**Comment by etxmato** [comment]
Hi there, you are right! Someone else reported this to me, I think end of last year and I have corrected it in the dev branch. Not sure but I don't think it is included in a released Emma 02 version as yet; it should be corrected in the latest beta release v1.47.14 (https://github.com/etxmato/emma_02_installation/tree/main/v1.47.14).

**Comment by gulrak** [comment]
Ah okay, thanks for the quick answer.

I would have expected the actual file to be updated on master of the source repository too, that is why I was irritated as it also has no dev branches visible. I would have made a PR but my own emulator doesn't have the file itself, it just uses change sets to the original CHIP-8 interpreter, like they where published originally.
So the release packages are not reproducible from this repository as it is behind the releases for the data files? If so, is that deliberately? As I normally don't constantly install new builds if I don't see relevant changes for me, especially if it is a pkg installer (I'm on macOS).
(Sorry if this is somewhere explained in the docs, please feel free to give me an rtfm if I missed that. :wink:)

In any way, as I don't need the file myself, if you say it's fixed, feel free to close the issue.
Thanks for looking into it.

**Comment by etxmato** [comment]
You are probably right that I should be a bit more carful with what I put in which branch. Basically I only use 2, dev and master; at every release I merge dev into the master branch but I don't do anything in between. I haven't done any release for a while now as I'm in the middle of a restructuring to use xml files instead of many gui tabs. In between all that I got my hands on the Cybervision 2001 ROM which made me develop an emulator for that so it stopped the whole xml thing for a while... anyway excuses, excuses ;)....
