### ISSUE TITLE
GUI hangs on Linux shortly after start-up

### ISSUE THREAD

**Issue by etxmato** [etxmato/emma_02#6]
- This doesn't happen on all occasions
- Also noticed on windows (on work laptop) that it hangs for about 30 seconds
- Possibly caused by the update check; maybe internet access is blocked by 'something', firewall or other?
- Maybe this should be 'default' off

**Comment by phiber1** [comment]
So far I'm testing (since yesterday) with updates disabled, and it hasn't happened again.
I'll continue testing.

**Comment by etxmato** [comment]
I believe this is now fixed by moving the update check to a separate thread, at least I haven't seen it anymore for a while; so closing it.
